//! MCP server.
//!
//! Same handler, two transports:
//! - `StreamableHttpService` mounted on the main axum listener at `/mcp`
//!   (see [`transport::build_http_service`]); MCP clients that speak HTTP/SSE
//!   (e.g. the MCP Inspector in remote mode) connect here.
//! - stdin/stdout via [`transport::run_stdio`], dispatched from the
//!   `branchwork-server mcp` subcommand; MCP clients that spawn the server
//!   as a child process (e.g. Claude Code) connect here.
//!
//! The handler is stateful: [`McpContext`] carries the plans directory and a
//! DB handle so tools can answer plan/task queries. Both transports take an
//! [`McpContext`] and plumb it into every instance the framework constructs.

pub mod tools;
pub mod transport;

use std::path::PathBuf;
use std::sync::{Arc, Mutex};

use rmcp::{
    ErrorData as McpError, ServerHandler,
    handler::server::router::tool::ToolRouter,
    model::{
        CallToolResult, Content, Implementation, ProtocolVersion, ServerCapabilities, ServerInfo,
    },
    tool, tool_handler, tool_router,
};
use tokio::sync::broadcast;

use crate::agents::AgentRegistry;
use crate::config::Effort;
use crate::db::Db;

/// Shared context injected into every [`BranchworkMcp`] instance. Cheap to
/// clone — `Db` is already `Arc<Mutex<_>>`, `AgentRegistry`/broadcast handles
/// are Arc-backed, and the remaining fields are small.
#[derive(Clone)]
pub struct McpContext {
    pub plans_dir: PathBuf,
    pub db: Db,
    /// In-process state shared with the running dashboard server. Present
    /// when the MCP service is mounted alongside the HTTP API (and also in
    /// stdio mode, since `branchwork-server mcp` boots its own channel/
    /// registry). Tools that mutate plan state use `broadcast_tx` to push
    /// live events to the dashboard and `registry`/`effort`/`port` to
    /// trigger auto-advance.
    pub broadcast_tx: broadcast::Sender<String>,
    pub registry: AgentRegistry,
    pub effort: Arc<Mutex<Effort>>,
    pub port: u16,
}

#[derive(Clone)]
pub struct BranchworkMcp {
    pub ctx: McpContext,
    // Consumed by code generated by #[tool_handler], which dead-code analysis
    // doesn't trace through the macro boundary.
    #[allow(dead_code)]
    tool_router: ToolRouter<BranchworkMcp>,
}

#[tool_router(router = hello_router, vis = "pub")]
impl BranchworkMcp {
    pub fn new(ctx: McpContext) -> Self {
        Self {
            ctx,
            tool_router: Self::hello_router() + Self::plans_router() + Self::status_router(),
        }
    }

    #[tool(description = "Return a greeting from the Branchwork MCP server")]
    fn hello(&self) -> Result<CallToolResult, McpError> {
        Ok(CallToolResult::success(vec![Content::text(
            "hello from Branchwork",
        )]))
    }
}

#[tool_handler(router = self.tool_router)]
impl ServerHandler for BranchworkMcp {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
            .with_server_info(Implementation::from_build_env())
            .with_protocol_version(ProtocolVersion::V_2024_11_05)
            .with_instructions(
                "Branchwork MCP server. Tools: hello, list_plans, get_plan, get_task, \
                 get_task_context, update_task_status, report_cost, report_blocker."
                    .to_string(),
            )
    }
}
